apiVersion: v1
kind: Secret
metadata:
  name: mlflow-db-credentials
  namespace: redhat-ods-applications
type: Opaque
stringData:
  BACKEND_STORE_URI: "postgresql://maas:maas_PASS@maas-postgres.redhat-ods-applications.svc.cluster.local:5432/mlflow_db?sslmode=disable"
