apiVersion: v1
kind: Secret
metadata:
  name: maas-db-config
  namespace: redhat-ods-applications
type: Opaque
stringData:
  DB_CONNECTION_URL: "postgresql://maas:maas_PASS@maas-postgres.redhat-ods-applications.svc.cluster.local:5432/maas_db"
