apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: maas-postgres-pvc
  namespace: redhat-ods-applications
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
